# Generated by Django 5.2.1 on 2025-07-16 23:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 7, 16, 23, 36, 21, 601917, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deck',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='deck',
            name='last_reviewed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
