# Generated by Django 5.2.1 on 2025-07-18 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0003_card_created_at_card_difficulty_card_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='difficulty',
            field=models.CharField(choices=[('again', 'Again'), ('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=20),
        ),
    ]
