# Generated by Django 5.2.1 on 2025-07-20 21:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0004_alter_card_difficulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='shared_with',
            field=models.ManyToManyField(blank=True, related_name='shared_decks', to=settings.AUTH_USER_MODEL),
        ),
    ]
