# Generated by Django 5.2.1 on 2025-07-20 22:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0005_deck_shared_with'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deck',
            name='shared_with',
        ),
        migrations.AddField(
            model_name='deck',
            name='share_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
