# Generated by Django 5.2.1 on 2025-07-20 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0006_remove_deck_shared_with_deck_share_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deck',
            name='share_token',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
